/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jobber.gui.trabalhador;

import java.util.ArrayList;

import javax.swing.table.DefaultTableModel;

import jobber.backend.Conexao;
import jobber.backend.trabalhador.GerenciarTrabalho;
import jobber.gui.cliente.*;
import jobber.modelo.Conta;
import jobber.modelo.Feedback;
import jobber.modelo.Trabalho;

/**
 *
 * @author rfutenma
 */
public class IFrm_Feedbacks extends javax.swing.JInternalFrame {


    Conexao conexao;
    Trabalho trabalho;
    Conta conta;
    ArrayList<Feedback> feedbacks;

    /**
     * Creates new form IFrm_Combinando
     */
    public IFrm_Feedbacks() {
        initComponents();
    }

    public IFrm_Feedbacks(Conexao conexao, Trabalho trabalho, Conta conta) {
        this.conexao = conexao;
        this.trabalho = trabalho;
        this.conta = conta;
        initComponents();
        init();
    }

    public void  init() {
        txt_nome.setText(this.trabalho.getNome());
        txt_nome.setEnabled(false);
        txt_id.setText(String.valueOf(this.trabalho.getId()));
        txt_notamedia.setText(String.valueOf( (this.trabalho.getSomaNotaDeFeedback()/this.trabalho.getQntDeFeedback()) ));
        if(txt_notamedia.getText().equals("NaN")) txt_notamedia.setText(0+"");
        GerenciarTrabalho gerenciarTrabalho = new GerenciarTrabalho(this.conexao);
        feedbacks = gerenciarTrabalho.listaFeedbackByTrabalho(this.trabalho);
        DefaultTableModel dtm = (DefaultTableModel) tbl_feedbacks.getModel();

        dtm.setNumRows(0);
        for(Feedback feedback: this.feedbacks) {

            dtm.addRow(new Object[]{
                    feedback.getComentario(),
                    feedback.getNota(),
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_voltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_notamedia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_feedbacks = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Feedbacks");
        setMaximumSize(new java.awt.Dimension(500, 450));
        setMinimumSize(new java.awt.Dimension(500, 450));
        setPreferredSize(new java.awt.Dimension(500, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Feedbacks");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        btn_voltar.setText("< Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel2.setText("Nome do trabalho:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));
        getContentPane().add(txt_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 250, 20));

        jLabel4.setText("id:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        txt_notamedia.setEnabled(false);
        getContentPane().add(txt_notamedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 60, -1));

        tbl_feedbacks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Comentário", "Nota"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_feedbacks);
        if (tbl_feedbacks.getColumnModel().getColumnCount() > 0) {
            tbl_feedbacks.getColumnModel().getColumn(0).setResizable(false);
            tbl_feedbacks.getColumnModel().getColumn(0).setPreferredWidth(500);
            tbl_feedbacks.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 430, 180));

        jLabel3.setText("Nota Média:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        txt_id.setEnabled(false);
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        IFrm_GerenciarTrab tela = new IFrm_GerenciarTrab(conexao, conta);        
        getParent().add(tela);
        int x = (getParent().getWidth()/2) - tela.getWidth()/2;
        int y = (getParent().getHeight()/2) - tela.getHeight()/2;
        tela.setLocation(x, y);
        tela.setVisible(true);
        this.dispose();  
    }//GEN-LAST:event_btn_voltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_feedbacks;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_notamedia;
    // End of variables declaration//GEN-END:variables
}
