/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jobber.gui.trabalhador;

import javax.swing.JOptionPane;
import jobber.gui.cliente.*;

/**
 *
 * @author rfutenma
 */
public class IFrm_GerenciarTrab extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrm_Combinando
     */
    public IFrm_GerenciarTrab() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_feedbacks = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_trabalhos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_adicionar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Gerenciar Trabalhos");
        setMaximumSize(new java.awt.Dimension(500, 450));
        setMinimumSize(new java.awt.Dimension(500, 450));
        setPreferredSize(new java.awt.Dimension(500, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_feedbacks.setText("Feedbacks");
        btn_feedbacks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_feedbacksActionPerformed(evt);
            }
        });
        getContentPane().add(btn_feedbacks, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        tbl_trabalhos.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tbl_trabalhos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "Nome do trabalho", "Nota"
            }
        ) {
            Class[] types = new Class [] {
                Integer.class, Object.class, Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_trabalhos);
        if (tbl_trabalhos.getColumnModel().getColumnCount() > 0) {
            tbl_trabalhos.getColumnModel().getColumn(0).setMinWidth(0);
            tbl_trabalhos.getColumnModel().getColumn(0).setPreferredWidth(0);
            tbl_trabalhos.getColumnModel().getColumn(0).setMaxWidth(0);
            tbl_trabalhos.getColumnModel().getColumn(1).setResizable(false);
            tbl_trabalhos.getColumnModel().getColumn(1).setPreferredWidth(350);
            tbl_trabalhos.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 440, 310));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Gerenciar Trabalhos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        btn_adicionar.setText("Adicionar");
        btn_adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_adicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_feedbacksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_feedbacksActionPerformed
         
    }//GEN-LAST:event_btn_feedbacksActionPerformed

    private void btn_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adicionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_adicionarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_adicionar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_feedbacks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_trabalhos;
    // End of variables declaration//GEN-END:variables
}
