/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jobber.gui.cliente;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import jobber.backend.Conexao;
import jobber.backend.Combinando;
import jobber.backend.trabalhador.GerenciarTrabalho;
import jobber.gui.trabalhador.*;
import jobber.modelo.Conta;
import jobber.modelo.Feedback;
import jobber.modelo.Processo;
import jobber.modelo.Trabalho;

/**
 *
 * @author rfutenma
 */
public class IFrm_Trabalho extends javax.swing.JInternalFrame {
    
    Conexao conexao;
    Conta conta;
    Trabalho trabalho;
    ArrayList<Feedback> feedbacks;
    /**
     * Creates new form IFrm_Combinando
     */
    public IFrm_Trabalho() {
        initComponents();
    }
    
    public IFrm_Trabalho(Conexao conexao, Conta conta, Trabalho trabalho){
        this.conexao = conexao;
        this.conta = conta;
        this.trabalho = trabalho;
        initComponents();
        init();
    }
    
    private void init(){
        txt_id.setText(""+trabalho.getId());
        txt_nome.setText(trabalho.getNome());
        txt_desc.setText(trabalho.getDescricao());
        txt_notamedia.setText(String.valueOf( (this.trabalho.getSomaNotaDeFeedback()/this.trabalho.getQntDeFeedback()) ));
        if(txt_notamedia.getText().equals("NaN")) txt_notamedia.setText(0+"");
        GerenciarTrabalho gerenciarTrabalho = new GerenciarTrabalho(this.conexao);
        feedbacks = gerenciarTrabalho.listaFeedbackByTrabalho(this.trabalho);
        DefaultTableModel dtm = (DefaultTableModel) tbl_comentarios.getModel();

        dtm.setNumRows(0);
        for(Feedback feedback: this.feedbacks) {

            dtm.addRow(new Object[]{
                    feedback.getComentario(),
                    feedback.getNota(),
            });
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_voltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_desc = new javax.swing.JTextArea();
        btn_combinar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_notamedia = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_comentarios = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setTitle("Buscar Trabalho");
        setMaximumSize(new java.awt.Dimension(500, 450));
        setMinimumSize(new java.awt.Dimension(500, 450));
        setPreferredSize(new java.awt.Dimension(500, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText(""+trabalho.getNome());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        btn_voltar.setText("< Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel2.setText("Nome do trabalho:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));
        getContentPane().add(txt_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 330, 20));

        jLabel3.setText("Descrição:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        txt_desc.setColumns(20);
        txt_desc.setRows(5);
        jScrollPane2.setViewportView(txt_desc);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 330, 60));

        btn_combinar.setText("Combinar");
        btn_combinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_combinarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_combinar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));

        jLabel4.setText("id:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        txt_id.setEnabled(false);
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 70, -1));

        jLabel5.setText("Nota Média:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        txt_notamedia.setEnabled(false);
        getContentPane().add(txt_notamedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 60, -1));

        tbl_comentarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Comentário", "Nota"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbl_comentarios);
        if (tbl_comentarios.getColumnModel().getColumnCount() > 0) {
            tbl_comentarios.getColumnModel().getColumn(0).setResizable(false);
            tbl_comentarios.getColumnModel().getColumn(0).setPreferredWidth(350);
            tbl_comentarios.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 420, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_combinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_combinarActionPerformed
        Processo processo;
        Combinando comb = new Combinando(conexao);
        processo = comb.criaProcesso(trabalho, conta);       
        IFrm_ChatCli tela= new IFrm_ChatCli(conexao, conta, processo);
        getParent().add(tela);
        int x = (getParent().getWidth()/2) - tela.getWidth()/2;
        int y = (getParent().getHeight()/2) - tela.getHeight()/2;
        tela.setLocation(x, y);
        tela.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_combinarActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        IFrm_BuscarTrab tela = new IFrm_BuscarTrab(conexao,conta);
        getParent().add(tela);
        int x = (getParent().getWidth()/2) - tela.getWidth()/2;
        int y = (getParent().getHeight()/2) - tela.getHeight()/2;
        tela.setLocation(x, y);
        tela.setVisible(true);
        this.dispose();  
    }//GEN-LAST:event_btn_voltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_combinar;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbl_comentarios;
    private javax.swing.JTextArea txt_desc;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_notamedia;
    // End of variables declaration//GEN-END:variables
}
